packages:
  - "apps/*"
  - "packages/*"

catalogMode: prefer
catalogs:

  build:
    '@nuxt/devtools': ^2.6.5
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.1.2
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.2
    '@unocss/preset-web-fonts': ^66.5.4
    '@unocss/nuxt': ^66.5.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.9.0
    nuxt: ^4.1.2
    unocss: ^66.5.2
    unplugin: ^2.3.10
    vite: ^7.1.8

  dev:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1

  arena:
    '@vueuse/core': ^13.9.0
    pinia: ^3.0.3
    vue: ^3.5.22

  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4
  conflicts_@unocss/preset-web-fonts_h66_5_:
    '@unocss/preset-web-fonts': ^66.5.
  conflicts_@unocss/preset-web-fonts_h66_5:
    '@unocss/preset-web-fonts': ^66.5
  conflicts_@unocss/preset-web-fonts_h66_:
    '@unocss/preset-web-fonts': ^66.
  conflicts_@unocss/preset-web-fonts_h6:
    '@unocss/preset-web-fonts': ^6
  conflicts_@unocss/preset-web-fonts_h:
    '@unocss/preset-web-fonts': ^
  conflicts_@unocss/preset-web-fonts_:
    '@unocss/preset-web-fonts': ''
  conflicts_@unocss/preset-web-fonts_c:
    '@unocss/preset-web-fonts': c
  conflicts_@unocss/preset-web-fonts_ca:
    '@unocss/preset-web-fonts': ca
  conflicts_@unocss/preset-web-fonts_cat:
    '@unocss/preset-web-fonts': cat
  conflicts_@unocss/preset-web-fonts_cata:
    '@unocss/preset-web-fonts': cata
  conflicts_@unocss/preset-web-fonts_catal:
    '@unocss/preset-web-fonts': catal
  conflicts_@unocss/preset-web-fonts_catalo:
    '@unocss/preset-web-fonts': catalo
  conflicts_@unocss/preset-web-fonts_catalog:
    '@unocss/preset-web-fonts': catalog

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - simple-git-hooks
catalog:
  '@unocss/preset-web-fonts': ^66.5.4
