packages:
  - "apps/*"
  - "packages/*"

shamefullyHoist: true
autoInstallPeers: true

catalogs:

  build:
    '@nuxt/devtools': ^2.6.5
    '@nuxt/eslint': ^1.9.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': 66.5.2
    '@unocss/preset-web-fonts': 66.5.2
    '@unocss/preset-mini': 66.5.2
    '@unocss/nuxt': 66.5.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.9.0
    nuxt: ^4.1.2
    ethers: ^6.15.0

  dev:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1
    '@hashgraph/hedera-wallet-connect': 1.5.1
    '@hashgraph/sdk': 2.74.0
    '@walletconnect/modal': 2.7.0
    p5i: ^0.6.0

  arena:
    '@vueuse/core': ^13.9.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    tailwind-merge: ^3.3.1
    '@tanstack/vue-table': ^8.21.3
    pinia: ^3.0.3
    vue: ^3.5.22
    '@unhead/schema': ^2.0.19
    floating-vue: ^5.2.2
    '@iconify-emoji/twemoji': ^1.0.2
    tiny-decode: ^0.1.3
    simple-git: ^3.28.0
    std-env: ^3.10.0
    nuxt-security: ^2.4.0
    '@unlazy/nuxt': ^1.0.0
    '@vue-macros/nuxt': ^3.1.1
    postcss-nested: ^7.0.2
    '@fnando/sparkline': ^0.3.10
    '@iconify/json': ^2.2.170
    '@iconify/utils': ^2.1.22
    '@intlify/core-base': ^11.1.12
    '@intlify/message-compiler': ^11.1.12
    '@intlify/shared': ^11.1.12
    '@nuxtjs/i18n': ^10.1.0
    '@tanstack/vue-query': ^5.90.5
    '@vueuse/gesture': ^2.0.0
    '@vueuse/integrations': ^12.0.0
    '@vueuse/math': ^12.0.0
    '@vueuse/motion': 2.2.6
    '@vueuse/shared': ^13.9.0
    '@wagmi/connectors': ^6.0.1
    '@wagmi/core': ^2.22.1
    '@wagmi/vue': ^0.2.13
    blurhash: ^2.0.5
    browser-fs-access: ^0.38.0
    events: ^3.3.0
    file-saver: ^2.0.5
    focus-trap: ^7.5.1
    fuse.js: ^7.0.0
    slimeform: ^0.10.0
    string-length: ^5.0.1
    use-wagmi: ^1.5.0
    viem: ^2.38.3
    vue-advanced-cropper: ^2.8.9
    vue-i18n: ^11.1.12
    vue-virtual-scroller: 2.0.0-beta.8
    workbox-build: ^7.1.1
    workbox-cacheable-response: ^7.1.0
    workbox-expiration: ^7.1.0
    workbox-precaching: ^7.1.0
    workbox-routing: ^7.1.0
    workbox-strategies: ^7.1.0
    workbox-window: ^7.1.0

  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - simple-git-hooks
