packages:
  - "apps/*"
  - "packages/*"

catalogs:

  build:
    '@nuxt/devtools': ^2.6.5
    '@nuxt/eslint': ^1.9.0
    '@nuxt/kit': ^4.1.2
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': 66.5.2
    '@unocss/preset-web-fonts': 66.5.2
    '@unocss/preset-mini': 66.5.2
    '@unocss/nuxt': 66.5.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.9.0
    nuxt: ^4.1.2
    unocss: 66.5.2
    unplugin: ^2.3.10
    vite: ^7.1.8
    ethers: ^6.15.0

  dev:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    typescript: ^5.9.3
    vue-tsc: ^3.1.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1
    '@hashgraph/hedera-wallet-connect': 1.5.1
    '@hashgraph/sdk': 2.74.0
    '@walletconnect/modal': 2.7.0
    p5i: ^0.6.0

  arena:
    '@vueuse/core': ^13.9.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    tailwind-merge: ^3.3.1
    '@tanstack/vue-table': ^8.21.3
    pinia: ^3.0.3
    vue: ^3.5.22
    reka-ui: ^2.5.1
    unocss-preset-shadcn: ^1.0.1
    unocss-preset-animations: ^1.3.0

  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - simple-git-hooks
